import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Banner from "@/components/ui/Banner";
import { Navbar } from "@/layout/Navbar";
import Header from "@/layout/Header";
import Footer from "@/layout/Footer";
import { TooltipProvider } from "@/components/ui/tooltip";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}  `}>
        <TooltipProvider>
          <div className="z-50">
            <Navbar />
            <Header />
          </div>
          <div className="bg-[#fbfcfc] min-h-screen pt-10 ">{children}</div>
          <Footer />
        </TooltipProvider>
      </body>
    </html>
  );
}
